### ISSUE TITLE
How can I use fss to replicate this combination of selectors and combinators?

### ISSUE THREAD

**Issue by travis-leith** [Bjorn-Strom/FSS#25]
Looking through Devtools (F12) I have determined the style I need to override is this one

```css
.dx-datagrid-rowsview .dx-row-focused.dx-data-row .dx-command-edit:not(.dx-focused) .dx-link, .dx-datagrid-rowsview .dx-row-focused.dx-data-row > td:not(.dx-focused), .dx-datagrid-rowsview .dx-row-focused.dx-data-row > tr > td:not(.dx-focused) {
    background-color: #1f8fb9;
    color: #2a2a2a;
}
```

fss supports [combinators](https://bjorn-strom.github.io/FSS/#/page/combinators) and [selectors](https://bjorn-strom.github.io/FSS/#/page/attributeSelectors). Is it possible to replicate the above css so I can override the colors?

**Comment by Bjorn-Strom** [comment]
Hello @travis-leith.

You are correct that `:not` is not supported yet.
This is something I have been wanting to fix for a while - so I will prioritize that.

When it comes to your initial question I have not had time to **really** look at it yet as I am busy with work.

I will take a look at how this can be implemented with Fss as is as soon as I have time.

**Comment by travis-leith** [comment]
I have managed to narrow the scope of my issue by playing around in Devtools.

I have a grid and I am setting the font color of a cell depending on the value in the cell. To this end, fss is generating the following css

```css
.css647538688 {
    color: limegreen;
}
```

But the color contrast is not great when the row is focused, so I want to also include the following

```css
.dx-row-focused .css647538688 {
    color: white;
}
```

However, I don't see an obvious way to specify this in fss. For example

```F#
createFss [
        ! (Selector.Class "dx-row-focused") [ Color.white ]
    ]
```

generates
```css
.css1173998819 .dx-row-focused{color:white;}
```
