### ISSUE TITLE
FSS is not preserving the order of CSS declarations

### ISSUE THREAD

**Issue by BennieCopeland** [Bjorn-Strom/FSS#9]
The combinator that appears above the media query is generated after the media query in the CSS

```fsharp
let private titleStyle =
    fss [
        Display.flex
        FlexDirection.column
        AlignItems.center
        
        !> Html.H2 [
            Custom "margin-bottom" "16px !important"
        ]
        
        Media.query
               [ Fss.Types.Media.MinWidth (px section.firstBreakPoint)]
               [
                   FlexDirection.row
                   FlexGrow.value 1.0
                   
                   !> Html.H2 [
                       Custom "margin-bottom" "0px !important"
                       Custom "margin-right" "16px !important"
                       
                       LastChild [
                           Custom "margin-right" "0px !important"
                       ]
                   ]
               ]
               
        Label "SectionTitle"
    ]
```

```css
.css-707432800-SectionTitle {
    display: flex;
    flex-direction: column;
    align-items: center;
}

@media (min-width: 768px) {
    .css-707432800-SectionTitle {
        flex-direction: row;
        flex-grow: 1;
     }
    .css-707432800-SectionTitle > h2 {
        margin-bottom: 0px !important;
        margin-right: 16px !important;
    }
    .css-707432800-SectionTitle > h2:last-child {
        margin-right: 0px !important;
    }
}

.css-707432800-SectionTitle > h2 {
    margin-bottom: 16px !important;
}
```
